# Generated by Django 5.2.1 on 2025-05-26 10:05

import account.account_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='userauth',
            name='profile_pic',
            field=models.ImageField(blank=True, default='faces/profile.png', null=True, upload_to='faces/', validators=[account.account_utils.validate_image]),
        ),
    ]
