# Generated by Django 5.2.1 on 2025-05-26 13:48

import account.account_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userauth_options_alter_userauth_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/', validators=[account.account_utils.validate_image]),
        ),
    ]
