# Generated by Django 5.2.1 on 2025-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userauth_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
