# Generated by Django 5.2.4 on 2025-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userauth_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='club',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='playing_level',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
