# Generated by Django 5.2.4 on 2025-07-26 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('entry', 'Entry'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yearly_discount_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('free_monthly_tickets', models.PositiveIntegerField(default=0)),
                ('ticket_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='subscriptio_name_d6effc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_dee6c0_idx'), models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__8de137_idx')],
            },
        ),
    ]
