# Generated by Django 5.2.4 on 2025-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, default='abcd1234', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, default='efgh5678', max_length=255, null=True),
        ),
    ]
