# Generated by Django 5.2.4 on 2025-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_stripe_price_id_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
