# Generated by Django 5.2.4 on 2025-08-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_usage_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
