# Generated by Django 5.2.4 on 2025-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_usersubscription_last_usage_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='yearly_tickets_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
