# Generated by Django 5.2.4 on 2025-08-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_usersubscription_yearly_tickets_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='monthly_tickets_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
