# Generated by Django 5.2.4 on 2025-08-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_usersubscription_monthly_tickets_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
