# Generated by Django 5.2.4 on 2025-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscriptionplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='yearly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
