# Generated by Django 5.2.4 on 2025-08-02 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicketConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('unique_ticket_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_consolidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ticket Consolidation',
                'verbose_name_plural': 'User Ticket Consolidations',
                'indexes': [models.Index(fields=['user', 'email'], name='raffle_user_user_id_9a3285_idx'), models.Index(fields=['created_at'], name='raffle_user_created_ba0378_idx')],
            },
        ),
    ]
