# Generated by Django 5.2.4 on 2025-08-11 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_userticketconsolidationarchive_rafflewinner'),
        ('tickets', '0004_giveawayticket_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafflewinner',
            name='position',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='RaffleWinnerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('winning_ticket_id', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_winners', to='tickets.giveawayticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Raffle Winner',
                'verbose_name_plural': 'Archived Raffle Winners',
                'indexes': [models.Index(fields=['position', 'giveaway'], name='raffle_raff_positio_503603_idx')],
            },
        ),
    ]
