# Generated by Django 5.2.1 on 2025-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacysafety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Abrar Fahim', max_length=100)),
                ('email', models.EmailField(help_text='abc@gmail.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(help_text='Your message here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
