# Generated by Django 5.2.4 on 2025-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('subscription', 'Subscription'), ('first_time_bonus', 'First-Time Bonus'), ('purchase', 'Purchase')], default='purchase', max_length=50),
        ),
    ]
