# Generated by Django 5.2.4 on 2025-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpurchase_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='unique_ticket_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
