# Generated by Django 5.2.4 on 2025-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketpurchase_unique_ticket_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawayticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
